/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "lab3/stringChecker.h"
#include <gtest/gtest.h>
#include <cstdlib>

TEST(Lab3, TestEmpty) {
    char *string1 = new char[0];
    char *string2 = new char[0];

    cppLabMain3::Lab3 greeter;
    ASSERT_FALSE(greeter.checkChar(string1, string2));
    ASSERT_FALSE(greeter.checkStr(std::string(string1), std::string(string2)));
}

TEST(Lab3, SimpleTest) {
    char *string1 = new char[11]{"Big string"};
    char *string2 = new char[13]{"Small string"};

    cppLabMain3::Lab3 greeter;
    ASSERT_TRUE(greeter.checkChar(string1, string2));
    ASSERT_TRUE(greeter.checkStr(std::string(string1), std::string(string2)));
}

TEST(Lab3, SimpleFalseTest) {
    char *string1 = new char[5]{"Diff"};
    char *string2 = new char[6]{"erent"};

    cppLabMain3::Lab3 greeter;
    ASSERT_FALSE(greeter.checkChar(string1, string2));
    ASSERT_FALSE(greeter.checkStr(std::string(string1), std::string(string2)));
}