/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "lab1/monoLength.h"
#include <gtest/gtest.h>
#include <cstdlib>

TEST(Lab1, TestEmpty) {
    int length = 0;
    int arr[1];
    cppLabMain1::Lab1 greeter;
    int monoLengthValue = greeter.monoLength(arr, length);

    EXPECT_EQ(monoLengthValue, 0);
}

TEST(Lab1, TestUpper) {
    int length = 5;
    int arr[] = {1, 2, 3, 4, 5};
    cppLabMain1::Lab1 greeter;
    int monoLengthValue = greeter.monoLength(arr, length);

    EXPECT_EQ(monoLengthValue, 0);
}


TEST(Lab1, TestAll) {
    int length = 5;
    int arr[] = {5, 4, 3, 2, 1};
    cppLabMain1::Lab1 greeter;
    int monoLengthValue = greeter.monoLength(arr, length);

    EXPECT_EQ(monoLengthValue, 4);
}


TEST(Lab1, TestStart) {
    int length = 5;
    int arr[] = {5, 4, 3, 5, 1};
    cppLabMain1::Lab1 greeter;
    int monoLengthValue = greeter.monoLength(arr, length);

    EXPECT_EQ(monoLengthValue, 2);
}


TEST(Lab1, TestEnd) {
    int length = 5;
    int arr[] = {1, 2, 3, 3, 1};
    cppLabMain1::Lab1 greeter;
    int monoLengthValue = greeter.monoLength(arr, length);

    EXPECT_EQ(monoLengthValue, 1);
}


TEST(Lab1, TestMiddle) {
    int length = 5;
    int arr[] = {3, 4, 3, 4, 5};
    cppLabMain1::Lab1 greeter;
    int monoLengthValue = greeter.monoLength(arr, length);

    EXPECT_EQ(monoLengthValue, 1);
}


TEST(Lab1, TestOne) {
    int length = 1;
    int arr[] = {5};
    cppLabMain1::Lab1 greeter;
    int monoLengthValue = greeter.monoLength(arr, length);

    EXPECT_EQ(monoLengthValue, 0);
}


TEST(Lab1, TestTwo) {
    int length = 2;
    int arr[] = {5, 3};
    cppLabMain1::Lab1 greeter;
    int monoLengthValue = greeter.monoLength(arr, length);

    EXPECT_EQ(monoLengthValue, 1);
}


TEST(Lab1, TestTwoReverse) {
    int length = 2;
    int arr[] = {3, 5};
    cppLabMain1::Lab1 greeter;
    int monoLengthValue = greeter.monoLength(arr, length);

    EXPECT_EQ(monoLengthValue, 0);
}


TEST(Lab1, TestWTF) {
    int length = 6;
    int arr[] = {5, 4, 5, 3, 2, 1};
    cppLabMain1::Lab1 greeter;
    int monoLengthValue = greeter.monoLength(arr, length);

    EXPECT_EQ(monoLengthValue, 3);
}