/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "lab2/moduleMatrixSum.h"
#include <gtest/gtest.h>
#include <cstdlib>

TEST(Lab2, TestOptional) {
    int **arr = new int*[4]{new int[4]{3, 4, 5, 6}, new int[4]{3, 5, 6, 2}, new int[4]{1, 1, 2, 3}, new int[4]{4, 6, 2, 6}};
    int rows = 4;
    int columns = 4;
    cppLabMain2::Lab2 greeter;
    int **matrixSmoothingValue = greeter.matrixSmoothing(arr, rows, columns);
    int monoLengthValue = greeter.moduleMatrixSum(arr, rows, columns);

    EXPECT_EQ(monoLengthValue, 21);
}

TEST(Lab2, TestOptional2) {
    int **arr = new int*[4]{new int[4]{4, 2, 3, 2}, new int[4]{5, 3, 4, 1}, new int[4]{4, 2, 3, 3}, new int[4]{4, 3, 3, 2}};
    int rows = 4;
    int columns = 4;
    cppLabMain2::Lab2 greeter;
    int **matrixSmoothingValue = greeter.matrixSmoothing(arr, rows, columns);
    int monoLengthValue = greeter.moduleMatrixSum(arr, rows, columns);

    EXPECT_EQ(monoLengthValue, 21);
}

TEST(Lab2, TestOopsEmpty) {
    int **arr = new int*[4]{new int[4]{4, 2, 3, 2}, new int[1]{5}, new int[4]{4, 2, 3, 3}, new int[2]{4, 3}};
    int rows = 4;
    int columns = 4;
    cppLabMain2::Lab2 greeter;
    int **matrixSmoothingValue = greeter.matrixSmoothing(arr, rows, columns);
    int monoLengthValue = greeter.moduleMatrixSum(arr, rows, columns);

    EXPECT_EQ(monoLengthValue, 18);
}

TEST(Lab2, TestSimple) {
    int **arr = new int*[3]{new int[1]{1}, new int[1]{2}, new int[1]{3}};
    int rows = 4;
    int columns = 4;
    cppLabMain2::Lab2 greeter;
    int **matrixSmoothingValue = greeter.matrixSmoothing(arr, rows, columns);
    int monoLengthValue = greeter.moduleMatrixSum(arr, rows, columns);

    EXPECT_EQ(monoLengthValue, 3);
}

TEST(Lab2, TestEmpty) {
    int **arr = new int*[0];
    int rows = 0;
    int columns = 0;
    cppLabMain2::Lab2 greeter;
    int **matrixSmoothingValue = greeter.matrixSmoothing(arr, rows, columns);
    int monoLengthValue = greeter.moduleMatrixSum(arr, rows, columns);

    EXPECT_EQ(monoLengthValue, 0);
}