/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef APP_H
#define APP_H

#include <string>

namespace cppLabMain1 {
    class Lab1 {
        public:
        int monoLength(const int arr[], int length);
    };
}

#endif
