/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "lab1/monoLength.h"

int cppLabMain1::Lab1::monoLength(const int arr[], int length) {
    if (length < 2) {
        return 0;
    }
    int monoLength = 0;
    int monoLengthMax = 0;

    for (int i = 0; i < length - 1; ++i) {
        if (arr[i] > arr[i + 1]) {
            ++monoLength;
        } else {
            if (monoLength > monoLengthMax) {
                monoLengthMax = monoLength;
            }
            monoLength = 0;
        }
    }

    return monoLength > monoLengthMax ? monoLength : monoLengthMax;
}